namespace Snowflake.Data.Core
{
    internal enum SFSessionParameter
    {
        CLIENT_PREFETCH_THREADS,
        SERVICE_NAME,
        CLIENT_VALIDATE_DEFAULT_PARAMETERS,
        CLIENT_STAGE_ARRAY_BINDING_THRESHOLD,
        CLIENT_SESSION_KEEP_ALIVE,
        QUERY_CONTEXT_CACHE_SIZE,
        DATE_OUTPUT_FORMAT,
        TIME_OUTPUT_FORMAT,
        CLIENT_REQUEST_MFA_TOKEN,
        CLIENT_STORE_TEMPORARY_CREDENTIAL
    }
}
