#!/usr/bin/env python3
"""Write ci/mirroring/import_paths.bara.sky scoped to a mirror PR's changed files.

Copybara merge-import reconciles every managed path when baseline flags are
set. Limiting origin_files/destination_files to the PR's actual diff keeps
the internal import PR aligned with the mirror PR (e.g. 9 files, not 14).
"""

from __future__ import annotations

import argparse
import fnmatch
import json
import subprocess
import sys
from pathlib import Path

CONFIG_FILE = Path(__file__).resolve().parents[1] / "mirror_config.json"
OUTPUT = Path(__file__).resolve().parents[1] / "import_paths.bara.sky"


def load_config() -> dict:
    """Load mirror configuration from the generated JSON config file."""
    if not CONFIG_FILE.exists():
        print(
            f"ERROR: Config file not found: {CONFIG_FILE}\n"
            "Run the mirror config generator first.",
            file=sys.stderr,
        )
        sys.exit(1)
    return json.loads(CONFIG_FILE.read_text(encoding="utf-8"))


def _matches_any(path: str, patterns: list[str]) -> bool:
    return any(fnmatch.fnmatch(path, pattern) for pattern in patterns)


def is_mirrored_path(
    path: str,
    nomirror_paths: list[str],
    excluded_paths: list[str],
    excluded_path_overrides: list[str],
) -> bool:
    if _matches_any(path, nomirror_paths):
        return False
    if _matches_any(path, excluded_path_overrides):
        return True
    if _matches_any(path, excluded_paths):
        return False
    return True


def fetch_pr_files(mirror_repo: str, pr_number: str) -> list[str]:
    raw = subprocess.check_output(
        [
            "gh",
            "api",
            f"repos/{mirror_repo}/pulls/{pr_number}/files",
            "--paginate",
            "--jq",
            '.[] | .filename, (.previous_filename // empty)',
        ],
        text=True,
    ).splitlines()
    # Deduplicate while preserving order.
    seen: set[str] = set()
    result: list[str] = []
    for path in raw:
        if path and path not in seen:
            seen.add(path)
            result.append(path)
    return result


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Write ci/mirroring/import_paths.bara.sky for a mirror PR import.",
    )
    parser.add_argument("pr_number", help="Mirror pull request number")
    parser.add_argument(
        "--draft",
        action="store_true",
        help="Open the imported internal PR as a draft",
    )
    args = parser.parse_args()

    config = load_config()
    mirror_repo = config["mirror_repo"]
    nomirror_paths = config["nomirror_paths"]
    excluded_paths = config["import_excluded_paths"]
    excluded_path_overrides = config["import_excluded_path_overrides"]

    pr_files = fetch_pr_files(mirror_repo, args.pr_number)

    # Reject filenames containing glob metacharacters.
    # Internal-only files absent from the public repo could then appear as
    # deletions in the generated internal PR. Legitimate files never need
    # these characters in their names.
    GLOB_METACHAR_SET = set("*?[]")
    unsafe = [p for p in pr_files if GLOB_METACHAR_SET.intersection(p)]
    if unsafe:
        print(
            "ERROR: PR contains filenames with glob metacharacters "
            "(potential Copybara glob injection):",
            ", ".join(unsafe),
            file=sys.stderr,
        )
        sys.exit(1)

    mirrored = [
        path
        for path in pr_files
        if is_mirrored_path(path, nomirror_paths, excluded_paths, excluded_path_overrides)
    ]
    dropped = sorted(set(pr_files) - set(mirrored))

    if dropped:
        print(
            "Skipping paths outside the mirrored tree:",
            ", ".join(dropped),
            file=sys.stderr,
        )
    if not mirrored:
        print("No mirrored files to import from mirror PR", file=sys.stderr)
        sys.exit(1)

    OUTPUT.write_text(
        "# Generated by ci/mirroring/scripts/prepare_import_paths.py — do not edit.\n"
        f"IMPORT_FILE_GLOBS = {json.dumps(mirrored, indent=4)}\n"
        f"IMPORT_AS_DRAFT = {args.draft}\n",
        encoding="utf-8",
    )
    print(f"Import scoped to {len(mirrored)} file(s):", ", ".join(mirrored), file=sys.stderr)
    if args.draft:
        print("Imported internal PR will be opened as a draft", file=sys.stderr)


if __name__ == "__main__":
    main()
