name: Code standards check

# Triggers the workflow on pull request events but only for the master branch
on:
  pull_request:
    branches: [ master ]
  workflow_dispatch:
    inputs:
      logLevel:
        default: warning
        description: "Log level"
        required: true
      tags:
        description: "Linter"
        required: false
permissions: { }

concurrency:
  # older builds for the same pull request number or branch should be cancelled
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  run-linter:
    name: Run linter
    runs-on: windows-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3
        with:
          depth: 0

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '6.0.103'

      - name: Install dotnet format
        run: dotnet tool install -g dotnet-format

      - name: Add dotnet tools to PATH
        run: echo "$HOME/.dotnet/tools" >> $GITHUB_PATH

      - name: Run Linter Bash Script
        run: |
          bash ci/scripts/linter.sh
